modified:   src/Dockerfile

diff --git a/src/Dockerfile b/src/Dockerfile
--- a/src/Dockerfile
+++ b/src/Dockerfile
@@ -6,9 +6,9 @@ RUN cp /usr/share/zoneinfo/America/New_York /etc/localtime
 RUN date
 RUN nginx -v
 
-EXPOSE 80
+
 
 STOPSIGNAL SIGQUIT
 
 CMD ["nginx", "-g", "daemon off;]
-HEALTHCHECK --interval=60s --retries=5 CMD curl --fail http://127.0.0.1 || exit 1
+#HEALTHCHECK --interval=60s --retries=5 CMD curl --fail http://127.0.0.1 || exit 1
